export const ADD_MOVIE_HEART = "ADD_MOVIE_HEART";
export const REMOVE_MOVIE_HEART = "REMOVE_MOVIE_HEART";
export const ADD_SHOW_HEART = "ADD_SHOW_HEART";
export const REMOVE_SHOW_HEART = "REMOVE_SHOW_HEART";
export const ADD_PERSON_HEART = "ADD_PERSON_HEART";
export const REMOVE_PERSON_HEART = "REMOVE_PERSON_HEART";
