const seedMovies = {
	results: [
		{
			popularity: 268.411,
			vote_count: 233,
			video: false,
			poster_path: "/aQvJ5WPzZgYVDrxLX4R6cLJCEaQ.jpg",
			id: 454626,
			adult: false,
			backdrop_path: "/tCUcf3oNWMW8kwAj3WC6CvIN5ah.jpg",
			original_language: "en",
			original_title: "Sonic the Hedgehog",
			genre_ids: [ 28, 35, 878, 10751 ],
			title: "Sonic the Hedgehog",
			vote_average: 7.1,
			overview:
				"Based on the global blockbuster videogame franchise from Sega, Sonic the Hedgehog tells the story of the world’s speediest hedgehog as he embraces his new home on Earth. In this live-action adventure comedy, Sonic and his new best friend team up to defend the planet from the evil genius Dr. Robotnik and his plans for world domination.",
			release_date: "2020-02-12"
		},
		{
			popularity: 242.99,
			vote_count: 4106,
			video: false,
			poster_path: "/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
			id: 496243,
			adult: false,
			backdrop_path: "/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg",
			original_language: "ko",
			original_title: "기생충",
			genre_ids: [ 35, 18, 53 ],
			title: "Parasite",
			vote_average: 8.6,
			overview:
				"All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
			release_date: "2019-05-30"
		},
		{
			popularity: 149.999,
			vote_count: 685,
			video: false,
			poster_path: "/h4VB6m0RwcicVEZvzftYZyKXs6K.jpg",
			id: 495764,
			adult: false,
			backdrop_path: "/uozb2VeD87YmhoUP1RrGWfzuCrr.jpg",
			original_language: "en",
			original_title: "Birds of Prey (and the Fantabulous Emancipation of One Harley Quinn)",
			genre_ids: [ 28, 35, 80 ],
			title: "Birds of Prey (and the Fantabulous Emancipation of One Harley Quinn)",
			vote_average: 6.9,
			overview:
				"After her breakup with the Joker, Harley Quinn joins forces with singer Black Canary, assassin Huntress, and police detective Renee Montoya to help a young girl named Cassandra, who had a hit placed on her after she stole a rare diamond from crime lord Roman Sionis.",
			release_date: "2020-02-05"
		},
		{
			popularity: 121.807,
			vote_count: 2138,
			video: false,
			poster_path: "/pThyQovXQrw2m0s9x82twj48Jq4.jpg",
			id: 546554,
			adult: false,
			backdrop_path: "/cjTQSwcsfVdirSFSHNBXRGkxmWa.jpg",
			original_language: "en",
			original_title: "Knives Out",
			genre_ids: [ 35, 80, 18, 9648, 53 ],
			title: "Knives Out",
			vote_average: 7.8,
			overview:
				"When renowned crime novelist Harlan Thrombey is found dead at his estate just after his 85th birthday, the inquisitive and debonair Detective Benoit Blanc is mysteriously enlisted to investigate. From Harlan's dysfunctional family to his devoted staff, Blanc sifts through a web of red herrings and self-serving lies to uncover the truth behind Harlan's untimely death.",
			release_date: "2019-11-27"
		},
		{
			popularity: 110.378,
			vote_count: 1547,
			video: false,
			poster_path: "/jyw8VKYEiM1UDzPB7NsisUgBeJ8.jpg",
			id: 512200,
			adult: false,
			backdrop_path: "/zTxHf9iIOCqRbxvl8W5QYKrsMLq.jpg",
			original_language: "en",
			original_title: "Jumanji: The Next Level",
			genre_ids: [ 28, 12, 35, 14 ],
			title: "Jumanji: The Next Level",
			vote_average: 6.7,
			overview:
				"As the gang return to Jumanji to rescue one of their own, they discover that nothing is as they expect. The players will have to brave parts unknown and unexplored in order to escape the world’s most dangerous game.",
			release_date: "2019-12-04"
		},
		{
			popularity: 108.601,
			vote_count: 410,
			video: false,
			poster_path: "/5eNiYMu2GXCtNlDwMcJqKGVwyoX.jpg",
			id: 448119,
			adult: false,
			backdrop_path: "/lG802rseTZcN9mtLsQPVfApEVzM.jpg",
			original_language: "en",
			original_title: "Dolittle",
			genre_ids: [ 12, 35, 14 ],
			title: "Dolittle",
			vote_average: 6.4,
			overview:
				"After losing his wife seven years earlier, the eccentric Dr. John Dolittle, famed doctor and veterinarian of Queen Victoria’s England, hermits himself away behind the high walls of Dolittle Manor with only his menagerie of exotic animals for company. But when the young queen falls gravely ill, a reluctant Dolittle is forced to set sail on an epic adventure to a mythical island in search of a cure, regaining his wit and courage as he crosses old adversaries and discovers wondrous creatures.",
			release_date: "2020-01-01"
		},
		{
			popularity: 95.742,
			vote_count: 1903,
			video: false,
			poster_path: "/7GsM4mtM0worCtIVeiQt28HieeN.jpg",
			id: 515001,
			adult: false,
			backdrop_path: "/agoBZfL1q5G79SD0npArSlJn8BH.jpg",
			original_language: "en",
			original_title: "Jojo Rabbit",
			genre_ids: [ 35, 18, 10752 ],
			title: "Jojo Rabbit",
			vote_average: 8.1,
			overview:
				"A World War II satire that follows a lonely German boy whose world view is turned upside down when he discovers his single mother is hiding a young Jewish girl in their attic. Aided only by his idiotic imaginary friend, Adolf Hitler, Jojo must confront his blind nationalism.",
			release_date: "2019-10-18"
		},
		{
			popularity: 104.881,
			vote_count: 2662,
			video: false,
			poster_path: "/iZf0KyrE25z1sage4SYFLCCrMi9.jpg",
			id: 530915,
			adult: false,
			backdrop_path: "/2WgieNR1tGHlpJUsolbVzbUbE1O.jpg",
			original_language: "en",
			original_title: "1917",
			genre_ids: [ 28, 18, 10752 ],
			title: "1917",
			vote_average: 8.1,
			overview:
				"At the height of the First World War, two young British soldiers must cross enemy territory and deliver a message that will stop a deadly attack on hundreds of soldiers.",
			release_date: "2019-12-10"
		},
		{
			popularity: 87.226,
			vote_count: 1563,
			video: false,
			poster_path: "/6ApDtO7xaWAfPqfi2IARXIzj8QS.jpg",
			id: 359724,
			adult: false,
			backdrop_path: "/n3UanIvmnBlH531pykuzNs4LbH6.jpg",
			original_language: "en",
			original_title: "Ford v Ferrari",
			genre_ids: [ 28, 18 ],
			title: "Ford v Ferrari",
			vote_average: 7.8,
			overview:
				"American car designer Carroll Shelby and the British-born driver Ken Miles work together to battle corporate interference, the laws of physics, and their own personal demons to build a revolutionary race car for Ford Motor Company and take on the dominating race cars of Enzo Ferrari at the 24 Hours of Le Mans in France in 1966.",
			release_date: "2019-11-13"
		},
		{
			popularity: 77.504,
			vote_count: 420,
			video: false,
			poster_path: "/1DPUFG6QnGqzpvEaDEv7TaepycM.jpg",
			id: 458897,
			adult: false,
			backdrop_path: "/a0xTB1vBxMGt6LGG4N7k1wO9lfL.jpg",
			original_language: "en",
			original_title: "Charlie's Angels",
			genre_ids: [ 28, 12, 35 ],
			title: "Charlie's Angels",
			vote_average: 6.4,
			overview:
				"When a systems engineer blows the whistle on a dangerous technology, Charlie's Angels from across the globe are called into action, putting their lives on the line to protect society.",
			release_date: "2019-11-14"
		},
		{
			popularity: 67.773,
			vote_count: 829,
			video: false,
			poster_path: "/y95lQLnuNKdPAzw9F9Ab8kJ80c3.jpg",
			id: 38700,
			adult: false,
			backdrop_path: "/upUy2QhMZEmtypPW3PdieKLAHxh.jpg",
			original_language: "en",
			original_title: "Bad Boys for Life",
			genre_ids: [ 28, 80, 53 ],
			title: "Bad Boys for Life",
			vote_average: 6.4,
			overview:
				"Marcus and Mike are forced to confront new threats, career changes, and midlife crises as they join the newly created elite team AMMO of the Miami police department to take down the ruthless Armando Armas, the vicious leader of a Miami drug cartel.",
			release_date: "2020-01-15"
		},
		{
			popularity: 69.978,
			vote_count: 2969,
			video: false,
			poster_path: "/db32LaOibwEliAmSL2jjDF6oDdj.jpg",
			id: 181812,
			adult: false,
			backdrop_path: "/jOzrELAzFxtMx2I4uDGHOotdfsS.jpg",
			original_language: "en",
			original_title: "Star Wars: The Rise of Skywalker",
			genre_ids: [ 28, 12, 878 ],
			title: "Star Wars: The Rise of Skywalker",
			vote_average: 6.5,
			overview:
				"The surviving Resistance faces the First Order once again as the journey of Rey, Finn and Poe Dameron continues. With the power and knowledge of generations behind them, the final battle begins.",
			release_date: "2019-12-18"
		},
		{
			popularity: 63.225,
			vote_count: 104,
			video: false,
			poster_path: "/MBiKqTsouYqAACLYNDadsjhhC0.jpg",
			id: 486589,
			adult: false,
			backdrop_path: "/bga3i5jcejBekr2FCGJga1fYCh.jpg",
			original_language: "en",
			original_title: "Red Shoes and the Seven Dwarfs",
			genre_ids: [ 16, 10749 ],
			title: "Red Shoes and the Seven Dwarfs",
			vote_average: 6.5,
			overview:
				"Princes who have been turned into Dwarfs seek the red shoes of a lady in order to break the spell, although it will not be easy.",
			release_date: "2019-07-25"
		},
		{
			popularity: 69.714,
			vote_count: 3,
			video: false,
			poster_path: "/33VdppGbeNxICrFUtW2WpGHvfYc.jpg",
			id: 481848,
			adult: false,
			backdrop_path: "/yFRpUmsreYO5Bc0HVBTsJsHIIox.jpg",
			original_language: "en",
			original_title: "The Call of the Wild",
			genre_ids: [ 12, 18, 10751 ],
			title: "The Call of the Wild",
			vote_average: 5.5,
			overview: "A sled dog struggles for survival in the wilds of the Yukon.",
			release_date: "2020-02-19"
		},
		{
			popularity: 63.598,
			vote_count: 24,
			video: false,
			poster_path: "/qZ1KAgfdeNbzrNYKW4BIRHdEBJ9.jpg",
			id: 666750,
			adult: false,
			backdrop_path: "/6mKAKhj8POVGqV1GsroS5mGIUe9.jpg",
			original_language: "en",
			original_title: "Dragonheart: Vengeance",
			genre_ids: [ 14 ],
			title: "Dragonheart: Vengeance",
			vote_average: 6.6,
			overview:
				"Lukas, a young farmer whose family is killed by savage raiders in the countryside, sets out on an epic quest for revenge, forming an unlikely trio with a majestic dragon and a swashbuckling, sword-fighting mercenary, Darius.",
			release_date: "2020-02-04"
		},
		{
			popularity: 63.289,
			vote_count: 74,
			video: false,
			poster_path: "/8ZMrZGGW65ePWIgRn1260nA1uUm.jpg",
			id: 539537,
			adult: false,
			backdrop_path: "/dzfiE2VHY362dGI62XfZ2iI87CT.jpg",
			original_language: "en",
			original_title: "Fantasy Island",
			genre_ids: [ 14, 27, 878 ],
			title: "Fantasy Island",
			vote_average: 4.6,
			overview:
				"A group of contest winners arrive at an island hotel to live out their dreams, only to find themselves trapped in nightmare scenarios.",
			release_date: "2020-02-12"
		},
		{
			popularity: 57.485,
			vote_count: 278,
			video: false,
			poster_path: "/bSN9SysoRBMwJKNkfOlQlCw2YQO.jpg",
			id: 535292,
			adult: false,
			backdrop_path: "/5bUExJx4NLXJSaphRxO5VflaKdG.jpg",
			original_language: "en",
			original_title: "21 Bridges",
			genre_ids: [ 28, 80, 18 ],
			title: "21 Bridges",
			vote_average: 6.3,
			overview:
				"An embattled NYPD detective, is thrust into a citywide manhunt for a pair of cop killers after uncovering a massive and unexpected conspiracy. As the night unfolds, lines become blurred on who he is pursuing, and who is in pursuit of him.",
			release_date: "2019-10-24"
		},
		{
			popularity: 48.121,
			vote_count: 1451,
			video: false,
			poster_path: "/dtRbVsUb5O12WWO54SRpiMtHKC0.jpg",
			id: 338967,
			adult: false,
			backdrop_path: "/3ghImmHdp4RnC3UkL6hpLayclnb.jpg",
			original_language: "en",
			original_title: "Zombieland: Double Tap",
			genre_ids: [ 28, 35, 27 ],
			title: "Zombieland: Double Tap",
			vote_average: 6.9,
			overview:
				"Columbus, Tallahassee, Wichita, and Little Rock move to the American heartland as they face off against evolved zombies, fellow survivors, and the growing pains of the snarky makeshift family.",
			release_date: "2019-10-09"
		},
		{
			popularity: 41.869,
			vote_count: 24536,
			video: false,
			poster_path: "/qmDpIHrmpJINaRKAfWQfftjCdyi.jpg",
			id: 27205,
			adult: false,
			backdrop_path: "/s2bT29y0ngXxxu2IA8AOzzXTRhd.jpg",
			original_language: "en",
			original_title: "Inception",
			genre_ids: [ 28, 12, 878 ],
			title: "Inception",
			vote_average: 8.3,
			overview:
				"Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: \"inception\", the implantation of another person's idea into a target's subconscious.",
			release_date: "2010-07-15"
		},
		{
			popularity: 45.321,
			vote_count: 964,
			video: false,
			poster_path: "/7gOozJufKJ9WjcIs38KEs08Iq3D.jpg",
			id: 473033,
			adult: false,
			backdrop_path: "/5qTZGBHJNq6riBliYtOnH4yUN6x.jpg",
			original_language: "en",
			original_title: "Uncut Gems",
			genre_ids: [ 80, 18, 53 ],
			title: "Uncut Gems",
			vote_average: 7.2,
			overview:
				"A charismatic New York City jeweler always on the lookout for the next big score makes a series of high-stakes bets that could lead to the windfall of a lifetime. Howard must perform a precarious high-wire act, balancing business, family, and encroaching adversaries on all sides in his relentless pursuit of the ultimate win.",
			release_date: "2019-11-14"
		}
	],
	page: 1,
	total_results: 1036,
	dates: {
		maximum: "2020-02-25",
		minimum: "2020-01-08"
	},
	total_pages: 52
};

module.exports = seedMovies;
